### ISSUE TITLE
fatal error: DMAChannel.h: No such file or directory  #include "DMAChannel.h"

### ISSUE THREAD

**Issue by hitswa** [PaulStoffregen/OctoWS2811#10]
While implementing the code in Arduino for Uno i am getting this error
```
In file included from Adalight.ino:45:0:
OctoWS2811.h:28:24: fatal error: DMAChannel.h: No such file or directory
 #include "DMAChannel.h"
                        ^
compilation terminated.
Error compiling.
```
Kindly suggest the fix

**Comment by PaulStoffregen** [comment]
> Kindly suggest the fix

Use Teensy 3.2.

Arduino Uno and all 8 bit AVR boards are not supported.  They lack the special DMA hardware OctoWS2811 requires.
