### ISSUE TITLE
 WS2811_BRG

### ISSUE THREAD

**Issue by gibbedy** [PaulStoffregen/OctoWS2811#13]
Why no WS2811_BRG or WS2811_BGR?
Took me a while to get example "BasicTest" to show correct colors untill I added BRG for my strip.

Also I don't understand case WS2811_GBR bitmask

case WS2811_GBR:
  color = ((color<<8)&0xFFFF00) | ((color>>16)&0x0000FF);
  break;

Am I missing something?

**Comment by PaulStoffregen** [comment]
The input is RGB, the output is GBR.

    color = ((color<<8)&0xFFFF00) | ((color>>16)&0x0000FF);

Because "GB" are adjacent with both input and output, they can be shifted with only 1 operation which is more efficient.

**Comment by gibbedy** [comment]
Thanks Paul. 
Something similar I'm missing with my first issue as well?
