### ISSUE TITLE
Rainbow example doesn't properly set the first pixel with Arduino 1.8.2/Teensyduino 1.36

### ISSUE THREAD

**Issue by ssilverman** [PaulStoffregen/OctoWS2811#17]
Arduino 1.6.12 and Teensyduino 1.31 is the latest combination that works for this demo for me.

**Comment by PaulStoffregen** [comment]
Yup, looks like a bug was recently added which affects some (but not all) LED strips.

I will look into this within the next few weeks.

**Comment by SpencerGreene** [comment]
+1 on this.  happy to look into it if you have any guesses / hints where it might be?

**Comment by davydka** [comment]
Just ran into this issue as well!

**Comment by PaulStoffregen** [comment]
I've uploaded a new version with OctoWS2811 fixes.  Please give it a try and let me know if it solves this problem on your LED strips.

https://forum.pjrc.com/threads/44904-Teensyduino-1-37-Beta-3

**Comment by ssilverman** [comment]
It looks like that fixes it. Can a second party confirm this?

**Comment by PaulStoffregen** [comment]
Yes, several people have confirmed on the forum.

I'm closing this old issue.
