### ISSUE TITLE
In library.json, "url" should be "homepage"

### ISSUE THREAD

**Issue by ssilverman** [PaulStoffregen/OctoWS2811#25]
In library.json, `"url": "http://www.pjrc.com/teensy/td_libs_OctoWS2811.html"` should have `"homepage"` instead of `"url"`.
Ref: [library.json docs](http://docs.platformio.org/en/latest/librarymanager/config.html#homepage)

**Comment by PaulStoffregen** [comment]
Fixed.  Thanks.
