### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by xudonax** [PaulStoffregen/OctoWS2811#27]
I'm considering create a derivate work of this with support for up to 15 strips (based on [pull request 20 by ewust](https://github.com/PaulStoffregen/OctoWS2811/pull/20). Would that be okay? Would I need to do more than credit you for the original work?

In other words, is there any specific license that this project is under? Is it GPL, BSD, MIT or something else entirely?

**Comment by PaulStoffregen** [comment]
Refer to the license info in the source code comments.
