### ISSUE TITLE
Support for RGBW stripes

### ISSUE THREAD

**Issue by socke7** [PaulStoffregen/OctoWS2811#30]
Nowadays, these RGBW stripes are very common and should be supported here.
So far I've seen the GRBW configuration only, so I think this one should be implemented at least.

Thank you, very much!

**Comment by mikepurvis** [comment]
Looks to be done as of f7e98fdf77781ffb14733de5a283c4b6e675f646, but that's newer than the 1.4.0 version of the lib that Arduino's library manager tries to install.

**Comment by PaulStoffregen** [comment]
Created a 1.5 release.  Should fully resolve this.

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/OctoWS2811/releases/tag/1.5
