### ISSUE TITLE
PlatformIO directory problem

### ISSUE THREAD

**Issue by amittel** [PaulStoffregen/OctoWS2811#6]
Hi!
I installed your lib via
``platformio lib install 69``

But I got a compile error not finding the lib.

The problem was, that the files were in the wrong directory.
In Windows7 they were in
``%USER%\.platformio\lib\OctoWS2811_ID69\OctoWS2811``
but they should be in
``%USER%\.platformio\lib\OctoWS2811_ID69``

Copied ``OctoWS2811.cpp`` and ``OctoWS2811.h`` into ``OctoWS2811_ID69`` and now it works as expected.

**Comment by PaulStoffregen** [comment]
@ivankravets - Is this something I should fix here, or something needed inside Platform IO?

**Comment by ivankravets** [comment]
@PaulStoffregen please merge #7 

P.S: What do you think about [PlatformIO IDE for Atom](http://docs.platformio.org/en/latest/ide/atom.html) ?

**Comment by PaulStoffregen** [comment]
done

**Comment by PaulStoffregen** [comment]
> P.S: What do you think about PlatformIO IDE for Atom ?

This is the first I've seen it.  Too busy with urgent projects to try it right now... maybe in a couple months?

**Comment by ivankravets** [comment]
@amittel please `platformio lib update`. See http://platformio.org/#!/lib/show/69/OctoWS2811

**Comment by ivankravets** [comment]
> This is the first I've seen it. 

I've released first beta a few hours ago :blush: 

> Too busy with urgent projects to try it right now... maybe in a couple months?

Sure! I've just asked to "not try", but just take a look on the features. I think that it will be good alternative to users who want more than Arduino IDE. However, I don't know how Arduino community will react on it :(

**Comment by PaulStoffregen** [comment]
I get quite a few requests from people who want more powerful features than Arduino's simplistic IDE.  Maybe this will be a good path?

**Comment by ivankravets** [comment]
> Maybe this will be a good path?

I hope that YES. Some users say that the first PlatformIO IDE beta is "better 1000x" than current Arduino IDE. However, I'm not so optimistic in this comparison. Firstly, need to implement Library Manager and built-int Serial Monitor. Yes, PlatformIO DE contains built-in Terminal and user can use PlatformIO CLI within it, but they like GUI.

**Comment by PaulStoffregen** [comment]
Maybe start a thread on the forum, inviting people to give it a try?

https://forum.pjrc.com/forums/5-General-Discussion

**Comment by amittel** [comment]
Did the update and now everything looks good.

**Comment by ivankravets** [comment]
> Maybe start a thread on the forum, inviting people to give it a try?

@PaulStoffregen, could you pin this thread?

https://forum.pjrc.com/threads/33388-PlatformIO-IDE-The-next-generation-IDE-for-IoT-development?p=98647

Thanks!
